name: Create New Release

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "Version of the new image"
        required: true
        default: "latest"
      github_tag_version:
        description: "New Git Release Tag"
        required: true
        default: "v1.0"

env:
  IMAGE_NAME: frontend
  VERSION: ${{ github.event.inputs.image_version }}
  TAG: ${{ github.event.inputs.github_tag_version }}

jobs:
  create-new-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Project
        uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: Build frontend
        run: |
          cd webapp_frontend
          npm i
          npm run-script build
          cp -r build ../webapp_provider/public
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: Build and push
        run: |
          docker build -t filefighter/$IMAGE_NAME:$VERSION webapp_provider/
          IMAGE_ID=$(docker images $IMAGE_NAME -q)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker push filefighter/$IMAGE_NAME:$VERSION
      - name: Create new release and tag.
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          gzip: true
          files: deployment_files_${{ env.TAG }}:webapp_provider/
